export const SET_NEW_POST = 'PROFILE_SET_NEW_POST';
export const SET_USER_PROFILE = 'PROFILE_SET_USER_PROFILE';
export const SET_USER_STATUS = 'PROFILE_SET_USER_STATUS';
export const SET_USER_PHOTO_SUCCESS = 'PROFILE_SET_USER_PHOTO_SUCCESS';

export const SET_NEW_MESSAGE = 'DIALOGS_SET_NEW_MESSAGE';

export const FOLLOW = 'USERS_FOLLOW';
export const UNFOLLOW = 'USERS_UNFOLLOW';
export const SET_USERS = 'USERS_SET_USERS';
export const SET_TOTAL_COUNT_PAGES = 'USERS_SET_TOTAL_COUNT_PAGES';
export const SET_CURRENT_PAGE = 'USERS_SET_CURRENT_PAGE';
export const TOGGLE_IS_FETCHING = 'USERS_TOGGLE_IS_FETCHING';
export const TOGGLE_IS_FOLLOWING = 'USERS_TOGGLE_IS_FOLLOWING';

export const SET_USER_DATA = 'AUTH_SET_AUTH_USER_DATA';
export const SET_CURRENT_USER = 'AUTH_SET_CURRENT_USER';

export const SET_ERROR_MESSAGE = 'SECURITY_SET_ERROR_MESSAGE';
export const SET_CAPTCHA_URL = 'SECURITY_SET_CAPTCHA_URL';

export const INIT_APP_SUCCESS = 'APP_INIT_SUCCESS';
export const SET_APP_ERRORS = "APP_SET_ERRORS";

export const SET_FRIENDS = "NAVBAR_SET_FRIENDS";