export const SET_NEW_POST = 'SET_NEW_POST';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_USER_STATUS = 'SET_USER_STATUS';

export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE';

export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const SET_USERS = 'SET_USERS';
export const SET_TOTAL_COUNT_PAGES = 'SET_TOTAL_COUNT_PAGES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const TOGGLE_IS_FOLLOWING = 'TOGGLE_IS_FOLLOWING';

export const SET_USER_DATA = 'SET_AUTH_USER_DATA';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_CAPTCHA_URL = 'SET_CAPTCHA_URL';

export const APP_INIT_SUCCESS = 'APP_INIT_SUCCESS';